# Generated by Django 4.0.4 on 2022-07-25 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetail',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='orderdetail',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='orderdetail',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='orderdetail',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='orderdetail',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='orderdetail',
            name='updated_by',
        ),
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(max_length=10),
        ),
    ]
