# Generated by Django 4.0.4 on 2022-07-21 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_orderdetail_order_alter_orderdetail_variant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.BigIntegerField(default=0),
        ),
    ]
