<<<<<<< HEAD
# Generated by Django 4.0.4 on 2022-07-15 04:27
=======
# Generated by Django 4.0.4 on 2022-07-15 04:26
>>>>>>> 1c77aca27b4629f8db4d7f931284705172d7893d

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=255, null=True)),
                ('version', models.CharField(max_length=255, null=True)),
                ('size', models.CharField(max_length=255, null=True)),
                ('strap', models.CharField(max_length=255, null=True)),
                ('general', models.CharField(max_length=255, null=True)),
                ('utilities', models.CharField(max_length=255, null=True)),
                ('network', models.CharField(max_length=255, null=True)),
                ('storage', models.CharField(max_length=255, null=True)),
                ('os_cpu', models.CharField(max_length=255, null=True)),
                ('front_cam', models.CharField(max_length=255, null=True)),
                ('back_cam', models.CharField(max_length=255, null=True)),
                ('camera', models.CharField(max_length=255, null=True)),
                ('pin', models.CharField(max_length=255, null=True)),
                ('screen', models.CharField(max_length=255, null=True)),
                ('price', models.BigIntegerField(null=True)),
                ('sale', models.BigIntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_create_variant', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_delete_variant', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='products.product')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_update_variant', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
