# Generated by Django 4.0.4 on 2022-07-19 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('variants', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variant',
            name='back_cam',
        ),
    ]
