# Generated by Django 4.0.4 on 2022-07-19 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variants', '0002_remove_variant_back_cam'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
