# Generated by Django 4.0.4 on 2022-07-21 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variants', '0003_variant_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
