# Generated by Django 4.0.4 on 2022-07-20 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='rating',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
