<<<<<<< HEAD
# Generated by Django 4.0.4 on 2022-07-25 03:20
=======
# Generated by Django 4.0.4 on 2022-07-25 02:24
>>>>>>> b1016d3323a636ead81eab571b52925a8b7bc20c

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('variants', '0001_initial'),
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carts', to='variants.variant'),
        ),
    ]
