# Generated by Django 4.0.4 on 2022-07-15 04:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='tag',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='articles.tag'),
            preserve_default=False,
        ),
    ]
