# Generated by Django 4.0.4 on 2022-07-15 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_alter_article_updated_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='viewer',
            field=models.IntegerField(default=0),
        ),
    ]
