# Generated by Django 4.0.4 on 2022-07-15 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_alter_article_viewer'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='article',
            table='articles',
        ),
        migrations.AlterModelTable(
            name='tag',
            table='tag',
        ),
    ]
