# Generated by Django 4.0.4 on 2022-07-15 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='birthday',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='block_at',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='block_by',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
