<<<<<<< HEAD
# Generated by Django 4.0.4 on 2022-07-25 03:20
=======
# Generated by Django 4.0.4 on 2022-07-25 02:24
>>>>>>> b1016d3323a636ead81eab571b52925a8b7bc20c

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
    ]
