# Generated by Django 4.0.4 on 2022-07-19 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_managers'),
        ('accounts', '0004_alter_customuser_block_by_and_more'),
    ]

    operations = [
    ]
