# Generated by Django 4.0.4 on 2022-07-15 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_customuser_options_alter_customuser_table_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='address',
            table='address',
        ),
    ]
